// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleService.proto

package me.potato.grpc.lib;

public final class SampleServiceOuterClass {
	private SampleServiceOuterClass() {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
			(com.google.protobuf.ExtensionRegistryLite)registry);
	}

	public interface SampleOrBuilder extends
		// @@protoc_insertion_point(interface_extends:grpc_proto.Sample)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>uint32 id = 1;</code>
		 * @return The id.
		 */
		int getId();

		/**
		 * <code>string data = 2;</code>
		 * @return The data.
		 */
		java.lang.String getData();

		/**
		 * <code>string data = 2;</code>
		 * @return The bytes for data.
		 */
		com.google.protobuf.ByteString
		getDataBytes();
	}

	/**
	 * Protobuf type {@code grpc_proto.Sample}
	 */
	public static final class Sample extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:grpc_proto.Sample)
		SampleOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use Sample.newBuilder() to construct.
		private Sample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Sample() {
			data_ = "";
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(
			UnusedPrivateParameter unused) {
			return new Sample();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private Sample(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
				com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {

							id_ = input.readUInt32();
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();

							data_ = s;
							break;
						}
						default: {
							if (!parseUnknownField(
								input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_Sample_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_Sample_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					me.potato.grpc.lib.SampleServiceOuterClass.Sample.class, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder.class);
		}

		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>uint32 id = 1;</code>
		 * @return The id.
		 */
		@java.lang.Override
		public int getId() {
			return id_;
		}

		public static final int DATA_FIELD_NUMBER = 2;
		private volatile java.lang.Object data_;

		/**
		 * <code>string data = 2;</code>
		 * @return The data.
		 */
		@java.lang.Override
		public java.lang.String getData() {
			java.lang.Object ref = data_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String)ref;
			} else {
				com.google.protobuf.ByteString bs =
					(com.google.protobuf.ByteString)ref;
				java.lang.String s = bs.toStringUtf8();
				data_ = s;
				return s;
			}
		}

		/**
		 * <code>string data = 2;</code>
		 * @return The bytes for data.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString
		getDataBytes() {
			java.lang.Object ref = data_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
					com.google.protobuf.ByteString.copyFromUtf8(
						(java.lang.String)ref);
				data_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString)ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
			if (id_ != 0) {
				output.writeUInt32(1, id_);
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (id_ != 0) {
				size += com.google.protobuf.CodedOutputStream
					.computeUInt32Size(1, id_);
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof me.potato.grpc.lib.SampleServiceOuterClass.Sample)) {
				return super.equals(obj);
			}
			me.potato.grpc.lib.SampleServiceOuterClass.Sample other = (me.potato.grpc.lib.SampleServiceOuterClass.Sample)obj;

			if (getId()
				!= other.getId())
				return false;
			if (!getData()
				.equals(other.getData()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + ID_FIELD_NUMBER;
			hash = (53 * hash) + getId();
			hash = (37 * hash) + DATA_FIELD_NUMBER;
			hash = (53 * hash) + getData().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(me.potato.grpc.lib.SampleServiceOuterClass.Sample prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
				? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code grpc_proto.Sample}
		 */
		public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:grpc_proto.Sample)
			me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_Sample_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_Sample_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						me.potato.grpc.lib.SampleServiceOuterClass.Sample.class, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder.class);
			}

			// Construct using me.potato.grpc.lib.SampleServiceOuterClass.Sample.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
					.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				id_ = 0;

				data_ = "";

				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_Sample_descriptor;
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample getDefaultInstanceForType() {
				return me.potato.grpc.lib.SampleServiceOuterClass.Sample.getDefaultInstance();
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample build() {
				me.potato.grpc.lib.SampleServiceOuterClass.Sample result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample buildPartial() {
				me.potato.grpc.lib.SampleServiceOuterClass.Sample result = new me.potato.grpc.lib.SampleServiceOuterClass.Sample(this);
				result.id_ = id_;
				result.data_ = data_;
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof me.potato.grpc.lib.SampleServiceOuterClass.Sample) {
					return mergeFrom((me.potato.grpc.lib.SampleServiceOuterClass.Sample)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(me.potato.grpc.lib.SampleServiceOuterClass.Sample other) {
				if (other == me.potato.grpc.lib.SampleServiceOuterClass.Sample.getDefaultInstance())
					return this;
				if (other.getId() != 0) {
					setId(other.getId());
				}
				if (!other.getData().isEmpty()) {
					data_ = other.data_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
				me.potato.grpc.lib.SampleServiceOuterClass.Sample parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (me.potato.grpc.lib.SampleServiceOuterClass.Sample)e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int id_;

			/**
			 * <code>uint32 id = 1;</code>
			 * @return The id.
			 */
			@java.lang.Override
			public int getId() {
				return id_;
			}

			/**
			 * <code>uint32 id = 1;</code>
			 * @param value The id to set.
			 * @return This builder for chaining.
			 */
			public Builder setId(int value) {

				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>uint32 id = 1;</code>
			 * @return This builder for chaining.
			 */
			public Builder clearId() {

				id_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object data_ = "";

			/**
			 * <code>string data = 2;</code>
			 * @return The data.
			 */
			public java.lang.String getData() {
				java.lang.Object ref = data_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString)ref;
					java.lang.String s = bs.toStringUtf8();
					data_ = s;
					return s;
				} else {
					return (java.lang.String)ref;
				}
			}

			/**
			 * <code>string data = 2;</code>
			 * @return The bytes for data.
			 */
			public com.google.protobuf.ByteString
			getDataBytes() {
				java.lang.Object ref = data_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
							(java.lang.String)ref);
					data_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString)ref;
				}
			}

			/**
			 * <code>string data = 2;</code>
			 * @param value The data to set.
			 * @return This builder for chaining.
			 */
			public Builder setData(
				java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				data_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string data = 2;</code>
			 * @return This builder for chaining.
			 */
			public Builder clearData() {

				data_ = getDefaultInstance().getData();
				onChanged();
				return this;
			}

			/**
			 * <code>string data = 2;</code>
			 * @param value The bytes for data to set.
			 * @return This builder for chaining.
			 */
			public Builder setDataBytes(
				com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				data_ = value;
				onChanged();
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:grpc_proto.Sample)
		}

		// @@protoc_insertion_point(class_scope:grpc_proto.Sample)
		private static final me.potato.grpc.lib.SampleServiceOuterClass.Sample DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new me.potato.grpc.lib.SampleServiceOuterClass.Sample();
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.Sample getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Sample>
			PARSER = new com.google.protobuf.AbstractParser<Sample>() {
			@java.lang.Override
			public Sample parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new Sample(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Sample> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Sample> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public me.potato.grpc.lib.SampleServiceOuterClass.Sample getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface GetAllSamplesRequestOrBuilder extends
		// @@protoc_insertion_point(interface_extends:grpc_proto.GetAllSamplesRequest)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>uint32 max = 1;</code>
		 * @return The max.
		 */
		int getMax();

		/**
		 * <code>string data = 2;</code>
		 * @return The data.
		 */
		java.lang.String getData();

		/**
		 * <code>string data = 2;</code>
		 * @return The bytes for data.
		 */
		com.google.protobuf.ByteString
		getDataBytes();
	}

	/**
	 * Protobuf type {@code grpc_proto.GetAllSamplesRequest}
	 */
	public static final class GetAllSamplesRequest extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:grpc_proto.GetAllSamplesRequest)
		GetAllSamplesRequestOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use GetAllSamplesRequest.newBuilder() to construct.
		private GetAllSamplesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private GetAllSamplesRequest() {
			data_ = "";
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(
			UnusedPrivateParameter unused) {
			return new GetAllSamplesRequest();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private GetAllSamplesRequest(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
				com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {

							max_ = input.readUInt32();
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();

							data_ = s;
							break;
						}
						default: {
							if (!parseUnknownField(
								input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesRequest_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesRequest_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.class, me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.Builder.class);
		}

		public static final int MAX_FIELD_NUMBER = 1;
		private int max_;

		/**
		 * <code>uint32 max = 1;</code>
		 * @return The max.
		 */
		@java.lang.Override
		public int getMax() {
			return max_;
		}

		public static final int DATA_FIELD_NUMBER = 2;
		private volatile java.lang.Object data_;

		/**
		 * <code>string data = 2;</code>
		 * @return The data.
		 */
		@java.lang.Override
		public java.lang.String getData() {
			java.lang.Object ref = data_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String)ref;
			} else {
				com.google.protobuf.ByteString bs =
					(com.google.protobuf.ByteString)ref;
				java.lang.String s = bs.toStringUtf8();
				data_ = s;
				return s;
			}
		}

		/**
		 * <code>string data = 2;</code>
		 * @return The bytes for data.
		 */
		@java.lang.Override
		public com.google.protobuf.ByteString
		getDataBytes() {
			java.lang.Object ref = data_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
					com.google.protobuf.ByteString.copyFromUtf8(
						(java.lang.String)ref);
				data_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString)ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
			if (max_ != 0) {
				output.writeUInt32(1, max_);
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (max_ != 0) {
				size += com.google.protobuf.CodedOutputStream
					.computeUInt32Size(1, max_);
			}
			if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest)) {
				return super.equals(obj);
			}
			me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest other = (me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest)obj;

			if (getMax()
				!= other.getMax())
				return false;
			if (!getData()
				.equals(other.getData()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + MAX_FIELD_NUMBER;
			hash = (53 * hash) + getMax();
			hash = (37 * hash) + DATA_FIELD_NUMBER;
			hash = (53 * hash) + getData().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
				? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code grpc_proto.GetAllSamplesRequest}
		 */
		public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:grpc_proto.GetAllSamplesRequest)
			me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesRequest_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.class, me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.Builder.class);
			}

			// Construct using me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
					.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				max_ = 0;

				data_ = "";

				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesRequest_descriptor;
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest getDefaultInstanceForType() {
				return me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.getDefaultInstance();
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest build() {
				me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest buildPartial() {
				me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest result = new me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest(this);
				result.max_ = max_;
				result.data_ = data_;
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest) {
					return mergeFrom((me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest other) {
				if (other == me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest.getDefaultInstance())
					return this;
				if (other.getMax() != 0) {
					setMax(other.getMax());
				}
				if (!other.getData().isEmpty()) {
					data_ = other.data_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
				me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest)e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int max_;

			/**
			 * <code>uint32 max = 1;</code>
			 * @return The max.
			 */
			@java.lang.Override
			public int getMax() {
				return max_;
			}

			/**
			 * <code>uint32 max = 1;</code>
			 * @param value The max to set.
			 * @return This builder for chaining.
			 */
			public Builder setMax(int value) {

				max_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>uint32 max = 1;</code>
			 * @return This builder for chaining.
			 */
			public Builder clearMax() {

				max_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object data_ = "";

			/**
			 * <code>string data = 2;</code>
			 * @return The data.
			 */
			public java.lang.String getData() {
				java.lang.Object ref = data_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString)ref;
					java.lang.String s = bs.toStringUtf8();
					data_ = s;
					return s;
				} else {
					return (java.lang.String)ref;
				}
			}

			/**
			 * <code>string data = 2;</code>
			 * @return The bytes for data.
			 */
			public com.google.protobuf.ByteString
			getDataBytes() {
				java.lang.Object ref = data_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
							(java.lang.String)ref);
					data_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString)ref;
				}
			}

			/**
			 * <code>string data = 2;</code>
			 * @param value The data to set.
			 * @return This builder for chaining.
			 */
			public Builder setData(
				java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				data_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string data = 2;</code>
			 * @return This builder for chaining.
			 */
			public Builder clearData() {

				data_ = getDefaultInstance().getData();
				onChanged();
				return this;
			}

			/**
			 * <code>string data = 2;</code>
			 * @param value The bytes for data to set.
			 * @return This builder for chaining.
			 */
			public Builder setDataBytes(
				com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				data_ = value;
				onChanged();
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:grpc_proto.GetAllSamplesRequest)
		}

		// @@protoc_insertion_point(class_scope:grpc_proto.GetAllSamplesRequest)
		private static final me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest();
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<GetAllSamplesRequest>
			PARSER = new com.google.protobuf.AbstractParser<GetAllSamplesRequest>() {
			@java.lang.Override
			public GetAllSamplesRequest parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new GetAllSamplesRequest(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<GetAllSamplesRequest> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<GetAllSamplesRequest> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesRequest getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface GetAllSamplesResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:grpc_proto.GetAllSamplesResponse)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		java.util.List<me.potato.grpc.lib.SampleServiceOuterClass.Sample>
		getSamplesList();

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		me.potato.grpc.lib.SampleServiceOuterClass.Sample getSamples(int index);

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		int getSamplesCount();

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		java.util.List<? extends me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder>
		getSamplesOrBuilderList();

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder getSamplesOrBuilder(
			int index);
	}

	/**
	 * Protobuf type {@code grpc_proto.GetAllSamplesResponse}
	 */
	public static final class GetAllSamplesResponse extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:grpc_proto.GetAllSamplesResponse)
		GetAllSamplesResponseOrBuilder {
		private static final long serialVersionUID = 0L;

		// Use GetAllSamplesResponse.newBuilder() to construct.
		private GetAllSamplesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private GetAllSamplesResponse() {
			samples_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(
			UnusedPrivateParameter unused) {
			return new GetAllSamplesResponse();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private GetAllSamplesResponse(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
				com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 10: {
							if (!((mutable_bitField0_ & 0x00000001) != 0)) {
								samples_ = new java.util.ArrayList<me.potato.grpc.lib.SampleServiceOuterClass.Sample>();
								mutable_bitField0_ |= 0x00000001;
							}
							samples_.add(
								input.readMessage(me.potato.grpc.lib.SampleServiceOuterClass.Sample.parser(), extensionRegistry));
							break;
						}
						default: {
							if (!parseUnknownField(
								input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000001) != 0)) {
					samples_ = java.util.Collections.unmodifiableList(samples_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesResponse_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.class, me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.Builder.class);
		}

		public static final int SAMPLES_FIELD_NUMBER = 1;
		private java.util.List<me.potato.grpc.lib.SampleServiceOuterClass.Sample> samples_;

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		@java.lang.Override
		public java.util.List<me.potato.grpc.lib.SampleServiceOuterClass.Sample> getSamplesList() {
			return samples_;
		}

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		@java.lang.Override
		public java.util.List<? extends me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder>
		getSamplesOrBuilderList() {
			return samples_;
		}

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		@java.lang.Override
		public int getSamplesCount() {
			return samples_.size();
		}

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		@java.lang.Override
		public me.potato.grpc.lib.SampleServiceOuterClass.Sample getSamples(int index) {
			return samples_.get(index);
		}

		/**
		 * <code>repeated .grpc_proto.Sample samples = 1;</code>
		 */
		@java.lang.Override
		public me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder getSamplesOrBuilder(
			int index) {
			return samples_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
			for (int i = 0; i < samples_.size(); i++) {
				output.writeMessage(1, samples_.get(i));
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < samples_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
					.computeMessageSize(1, samples_.get(i));
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse)) {
				return super.equals(obj);
			}
			me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse other = (me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse)obj;

			if (!getSamplesList()
				.equals(other.getSamplesList()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (getSamplesCount() > 0) {
				hash = (37 * hash) + SAMPLES_FIELD_NUMBER;
				hash = (53 * hash) + getSamplesList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
				? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code grpc_proto.GetAllSamplesResponse}
		 */
		public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:grpc_proto.GetAllSamplesResponse)
			me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesResponse_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.class, me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.Builder.class);
			}

			// Construct using me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
					.alwaysUseFieldBuilders) {
					getSamplesFieldBuilder();
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				if (samplesBuilder_ == null) {
					samples_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					samplesBuilder_.clear();
				}
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return me.potato.grpc.lib.SampleServiceOuterClass.internal_static_grpc_proto_GetAllSamplesResponse_descriptor;
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse getDefaultInstanceForType() {
				return me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.getDefaultInstance();
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse build() {
				me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse buildPartial() {
				me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse result = new me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse(this);
				int from_bitField0_ = bitField0_;
				if (samplesBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0)) {
						samples_ = java.util.Collections.unmodifiableList(samples_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.samples_ = samples_;
				} else {
					result.samples_ = samplesBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse) {
					return mergeFrom((me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse other) {
				if (other == me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse.getDefaultInstance())
					return this;
				if (samplesBuilder_ == null) {
					if (!other.samples_.isEmpty()) {
						if (samples_.isEmpty()) {
							samples_ = other.samples_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureSamplesIsMutable();
							samples_.addAll(other.samples_);
						}
						onChanged();
					}
				} else {
					if (!other.samples_.isEmpty()) {
						if (samplesBuilder_.isEmpty()) {
							samplesBuilder_.dispose();
							samplesBuilder_ = null;
							samples_ = other.samples_;
							bitField0_ = (bitField0_ & ~0x00000001);
							samplesBuilder_ =
								com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
									getSamplesFieldBuilder() : null;
						} else {
							samplesBuilder_.addAllMessages(other.samples_);
						}
					}
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
				me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse)e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.util.List<me.potato.grpc.lib.SampleServiceOuterClass.Sample> samples_ =
				java.util.Collections.emptyList();

			private void ensureSamplesIsMutable() {
				if (!((bitField0_ & 0x00000001) != 0)) {
					samples_ = new java.util.ArrayList<me.potato.grpc.lib.SampleServiceOuterClass.Sample>(samples_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<
				me.potato.grpc.lib.SampleServiceOuterClass.Sample, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder, me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder> samplesBuilder_;

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public java.util.List<me.potato.grpc.lib.SampleServiceOuterClass.Sample> getSamplesList() {
				if (samplesBuilder_ == null) {
					return java.util.Collections.unmodifiableList(samples_);
				} else {
					return samplesBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public int getSamplesCount() {
				if (samplesBuilder_ == null) {
					return samples_.size();
				} else {
					return samplesBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample getSamples(int index) {
				if (samplesBuilder_ == null) {
					return samples_.get(index);
				} else {
					return samplesBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder setSamples(
				int index, me.potato.grpc.lib.SampleServiceOuterClass.Sample value) {
				if (samplesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSamplesIsMutable();
					samples_.set(index, value);
					onChanged();
				} else {
					samplesBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder setSamples(
				int index, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder builderForValue) {
				if (samplesBuilder_ == null) {
					ensureSamplesIsMutable();
					samples_.set(index, builderForValue.build());
					onChanged();
				} else {
					samplesBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder addSamples(me.potato.grpc.lib.SampleServiceOuterClass.Sample value) {
				if (samplesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSamplesIsMutable();
					samples_.add(value);
					onChanged();
				} else {
					samplesBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder addSamples(
				int index, me.potato.grpc.lib.SampleServiceOuterClass.Sample value) {
				if (samplesBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSamplesIsMutable();
					samples_.add(index, value);
					onChanged();
				} else {
					samplesBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder addSamples(
				me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder builderForValue) {
				if (samplesBuilder_ == null) {
					ensureSamplesIsMutable();
					samples_.add(builderForValue.build());
					onChanged();
				} else {
					samplesBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder addSamples(
				int index, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder builderForValue) {
				if (samplesBuilder_ == null) {
					ensureSamplesIsMutable();
					samples_.add(index, builderForValue.build());
					onChanged();
				} else {
					samplesBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder addAllSamples(
				java.lang.Iterable<? extends me.potato.grpc.lib.SampleServiceOuterClass.Sample> values) {
				if (samplesBuilder_ == null) {
					ensureSamplesIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(
						values, samples_);
					onChanged();
				} else {
					samplesBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder clearSamples() {
				if (samplesBuilder_ == null) {
					samples_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					samplesBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public Builder removeSamples(int index) {
				if (samplesBuilder_ == null) {
					ensureSamplesIsMutable();
					samples_.remove(index);
					onChanged();
				} else {
					samplesBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder getSamplesBuilder(
				int index) {
				return getSamplesFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder getSamplesOrBuilder(
				int index) {
				if (samplesBuilder_ == null) {
					return samples_.get(index);
				} else {
					return samplesBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public java.util.List<? extends me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder>
			getSamplesOrBuilderList() {
				if (samplesBuilder_ != null) {
					return samplesBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(samples_);
				}
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder addSamplesBuilder() {
				return getSamplesFieldBuilder().addBuilder(
					me.potato.grpc.lib.SampleServiceOuterClass.Sample.getDefaultInstance());
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder addSamplesBuilder(
				int index) {
				return getSamplesFieldBuilder().addBuilder(
					index, me.potato.grpc.lib.SampleServiceOuterClass.Sample.getDefaultInstance());
			}

			/**
			 * <code>repeated .grpc_proto.Sample samples = 1;</code>
			 */
			public java.util.List<me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder>
			getSamplesBuilderList() {
				return getSamplesFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<
				me.potato.grpc.lib.SampleServiceOuterClass.Sample, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder, me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder>
			getSamplesFieldBuilder() {
				if (samplesBuilder_ == null) {
					samplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
						me.potato.grpc.lib.SampleServiceOuterClass.Sample, me.potato.grpc.lib.SampleServiceOuterClass.Sample.Builder, me.potato.grpc.lib.SampleServiceOuterClass.SampleOrBuilder>(
						samples_,
						((bitField0_ & 0x00000001) != 0),
						getParentForChildren(),
						isClean());
					samples_ = null;
				}
				return samplesBuilder_;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:grpc_proto.GetAllSamplesResponse)
		}

		// @@protoc_insertion_point(class_scope:grpc_proto.GetAllSamplesResponse)
		private static final me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse();
		}

		public static me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<GetAllSamplesResponse>
			PARSER = new com.google.protobuf.AbstractParser<GetAllSamplesResponse>() {
			@java.lang.Override
			public GetAllSamplesResponse parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new GetAllSamplesResponse(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<GetAllSamplesResponse> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<GetAllSamplesResponse> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public me.potato.grpc.lib.SampleServiceOuterClass.GetAllSamplesResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
		internal_static_grpc_proto_Sample_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internal_static_grpc_proto_Sample_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor
		internal_static_grpc_proto_GetAllSamplesRequest_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internal_static_grpc_proto_GetAllSamplesRequest_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor
		internal_static_grpc_proto_GetAllSamplesResponse_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internal_static_grpc_proto_GetAllSamplesResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
		descriptor;

	static {
		java.lang.String[] descriptorData = {
			"\n\023sampleService.proto\022\ngrpc_proto\"\"\n\006Sam" +
				"ple\022\n\n\002id\030\001 \001(\r\022\014\n\004data\030\002 \001(\t\"1\n\024GetAllS" +
				"amplesRequest\022\013\n\003max\030\001 \001(\r\022\014\n\004data\030\002 \001(\t" +
				"\"<\n\025GetAllSamplesResponse\022#\n\007samples\030\001 \003" +
				"(\0132\022.grpc_proto.Sample2g\n\rSampleService\022" +
				"V\n\rGetAllSamples\022 .grpc_proto.GetAllSamp" +
				"lesRequest\032!.grpc_proto.GetAllSamplesRes" +
				"ponse\"\000B:\n\022me.potato.grpc.libZ$potato/de" +
				"mo-protocolbuffer-grpc/grpcb\006proto3"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
			.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[]{
				});
		internal_static_grpc_proto_Sample_descriptor =
			getDescriptor().getMessageTypes().get(0);
		internal_static_grpc_proto_Sample_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_grpc_proto_Sample_descriptor,
			new java.lang.String[]{"Id", "Data",});
		internal_static_grpc_proto_GetAllSamplesRequest_descriptor =
			getDescriptor().getMessageTypes().get(1);
		internal_static_grpc_proto_GetAllSamplesRequest_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_grpc_proto_GetAllSamplesRequest_descriptor,
			new java.lang.String[]{"Max", "Data",});
		internal_static_grpc_proto_GetAllSamplesResponse_descriptor =
			getDescriptor().getMessageTypes().get(2);
		internal_static_grpc_proto_GetAllSamplesResponse_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_grpc_proto_GetAllSamplesResponse_descriptor,
			new java.lang.String[]{"Samples",});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
